### ISSUE TITLE
TypeError: Descriptors cannot be created directly.

### ISSUE THREAD

**Issue by adithya-samavedhi** [mukhal/grace#2]
I tried running the inference by using the command mentioned in the README.
the command I run is:
`CUDA_VISIBLE_DEVICES=6,7 WANDB_MODE=disabled python run_grace.py \
                        --model_name_or_path mkhalifa/flan-t5-large-gsm8k \
                        --in_file data/gsm8k/dev.jsonl \
                        --task gsm8k \
                        --disc_path /data/adithya/ckpts/discrim/gsm8k/ \
                        --beta 0.1 --n_candidate_steps 20 --generation_type step-score \
                        --step_sampling_method top_p --device2 cuda:1 --top_p .95 --sample_calc true \
                        --max_steps 6  --max_step_length 60 --step_delimiter '|' --temperature .8  --n_self_consistency 1 --seed 42`
                        
 
I am running into an error by using the above command, however if I replace the model_name_or_path to "google/flan-t5-large", it does not give me an error. Could you please help me out here?

The following is the error:

```
args {
    "beta": 0.1,
    "bf16": false,
    "debug": false,
    "demos_file_name": "demos.jsonl",
    "device1": "cuda:0",
    "device2": "cuda:1",
    "disc_icl": false,
    "disc_path": "/data/adithya/ckpts/discrim/gsm8k/",
    "disc_step_score_aggregation": "mean",
    "eightbit": false,
    "generation_type": "step-score",
    "generator_batch_size": 32,
    "generator_beam_size": 3,
    "generator_only": false,
    "generator_sampling_method": "greedy",
    "goal": "eval",
    "icl": false,
    "in_file": "data/gsm8k/dev.jsonl",
    "instruction": null,
    "max_length": 256,
    "max_step_length": 60,
    "max_steps": 6,
    "model_name_or_path": "mkhalifa/flan-t5-large-gsm8k",
    "model_tokenizer_path": null,
    "n_candidate_steps": 20,
    "n_demos": 2,
    "n_examples": null,
    "n_samples_per_example": 10,
    "n_self_consistency": 1,
    "n_verifier_samples": 5,
    "normalize_disc_scores": true,
    "out_dir": null,
    "output_results_dir": null,
    "sample_calc": true,
    "seed": 42,
    "start_idx": 0,
    "step_delimiter": "|",
    "step_sampling_method": "top_p",
    "step_selection_method": "greedy",
    "task": "gsm8k",
    "temperature": 0.8,
    "top_k": 50,
    "top_p": 0.95,
    "use_verifier": false,
    "verbose": false,
    "verifier_batch_size": 32,
    "verifier_path": null
}
Traceback (most recent call last):
  File "/data/adithya/grace/run_grace.py", line 388, in <module>
    main(args)
  File "/data/adithya/grace/run_grace.py", line 29, in main
    tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path)
  File "/data/adithya/grace/transformers/src/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/data/adithya/grace/transformers/src/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/data/adithya/grace/transformers/src/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/data/adithya/grace/transformers/src/transformers/models/t5/tokenization_t5_fast.py", line 133, in __init__
    super().__init__(
  File "/data/adithya/grace/transformers/src/transformers/tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "/data/adithya/grace/transformers/src/transformers/convert_slow_tokenizer.py", line 1288, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "/data/adithya/grace/transformers/src/transformers/convert_slow_tokenizer.py", line 445, in __init__
    from .utils import sentencepiece_model_pb2 as model_pb2
  File "/data/adithya/grace/transformers/src/transformers/utils/sentencepiece_model_pb2.py", line 91, in <module>
    _descriptor.EnumValueDescriptor(
  File "/data/adithya/anaconda3/envs/grace/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

**Comment by Ber666** [comment]
Hi @mukhal , Adithya is from our LLM Reasoners team and working on including GRACE in our library. Would mind taking some time to look at this issue? Thanks!

**Comment by mukhal** [comment]
Sorry for the late response, for some reason I missed the issue. 

As the error message says, the solution is to downgrade protobuf. I think running `pip install protobuf==3.20.*` should solve the issue!
